language: php
# In order to use PHP 5.4/5.5, use Ubuntu 14 (Trusty) instead of the newer Ubuntu 16 (Xenial)
# https://docs.travis-ci.com/user/languages/php/#php-54x---55x-support-is-available-on-precise-and-trusty-only
dist: trusty
php:
  - "7.2"
  - "5.6"
  # swarm-01 uses PHP 5.4
  - "5.4"
install:
  - composer install
  # use Node.js 10 LTS
  - nvm install 10
  - node --version && npm install
script:
  - composer test
  - npm test
